export interface Improvement {
  name: string;
  description: string;
  costRub: number;
  timeDays: number;
  effectMs: number;
  applied?: boolean;
  // Новые эффекты на Web Vitals:
  fcpEffect?: number;
  lcpEffect?: number;
  inpEffect?: number;
  ttfbEffect?: number;
}

export type ImprovementGroup = Map<string, Improvement[]>;

export const improvements: ImprovementGroup = new Map([
  ['frontend', [
    { name: 'Минификация CSS и JS', timeDays: 2, costRub: 60000, effectMs: 180, description: 'Уменьшение размера файлов за счет удаления пробелов и комментариев' },
    { name: 'Использование lazy loading изображений', timeDays: 3, costRub: 80000, effectMs: 220, description: 'Загрузка изображений по мере прокрутки страницы' },
    { name: 'Оптимизация шрифтов', timeDays: 1, costRub: 40000, effectMs: 120, description: 'Использование форматов WOFF2 и preload шрифтов' },
    { name: 'Внедрение Service Worker', timeDays: 5, costRub: 150000, effectMs: 300, description: 'Кеширование статических ресурсов для офлайн-доступа' },
    { name: 'Разделение кода (Code Splitting)', timeDays: 4, costRub: 120000, effectMs: 260, description: 'Загрузка только нужных частей приложения' },
    { name: 'Оптимизация работы с DOM', timeDays: 2, costRub: 70000, effectMs: 150, description: 'Минимизация перерисовок и пересчетов стилей' },
    { name: 'Использование WebP изображений', timeDays: 3, costRub: 85000, effectMs: 210, description: 'Замена JPEG/PNG на WebP для уменьшения размера файлов' },
    { name: 'Уменьшение количества HTTP-запросов', timeDays: 2, costRub: 65000, effectMs: 170, description: 'Объединение файлов и кеширование' },
    { name: 'Установка Content Security Policy', timeDays: 1, costRub: 30000, effectMs: 80, description: 'Улучшение безопасности и производительности' },
    { name: 'Оптимизация анимаций CSS', timeDays: 2, costRub: 55000, effectMs: 130, description: 'Использование GPU-ускоренных анимаций' },
    { name: 'Использование HTTP/2 Server Push', timeDays: 3, costRub: 90000, effectMs: 200, description: 'Предварительная отправка ресурсов браузеру' },
    { name: 'Кеширование через Cache-Control', timeDays: 2, costRub: 60000, effectMs: 140, description: 'Эффективное управление кешированием' },
    { name: 'Оптимизация JavaScript Event Listeners', timeDays: 2, costRub: 60000, effectMs: 140, description: 'Минимизация количества и задержки событий' },
    { name: 'Использование WebAssembly', timeDays: 7, costRub: 250000, effectMs: 350, description: 'Перенос тяжелых вычислений в WebAssembly' },
    { name: 'Оптимизация изображений через CDN', timeDays: 3, costRub: 90000, effectMs: 190, description: 'Быстрая доставка изображений из ближайшего датацентра' },
    { name: 'Использование Prefetch и Preload', timeDays: 2, costRub: 60000, effectMs: 150, description: 'Предварительная загрузка критических ресурсов' },
    { name: 'Оптимизация Reactivity (Angular zone.js)', timeDays: 4, costRub: 110000, effectMs: 220, description: 'Минимизация ненужных обновлений UI' },
    { name: 'Lazy loading модулей Angular', timeDays: 4, costRub: 120000, effectMs: 230, description: 'Загрузка модулей по требованию' },
    { name: 'Оптимизация шейдеров WebGL', timeDays: 6, costRub: 180000, effectMs: 280, description: 'Ускорение графических операций' },
    { name: 'Использование CDN для библиотек', timeDays: 3, costRub: 80000, effectMs: 170, description: 'Быстрая загрузка библиотек с CDN' },
  ]],
  ['ssr', [
    { name: 'Кеширование SSR-результатов', timeDays: 5, costRub: 150000, effectMs: 300, description: 'Кеширование отрендеренных страниц' },
    { name: 'Оптимизация шаблонов', timeDays: 3, costRub: 90000, effectMs: 180, description: 'Упрощение и оптимизация шаблонов' },
    { name: 'Использование Incremental Static Regeneration', timeDays: 7, costRub: 200000, effectMs: 350, description: 'Часть страниц обновляется статически' },
    { name: 'SSR с использованием Edge Rendering', timeDays: 6, costRub: 180000, effectMs: 320, description: 'Быстрая отрисовка ближе к пользователю' },
    { name: 'Оптимизация рендеринга React/Angular', timeDays: 4, costRub: 120000, effectMs: 260, description: 'Ускорение виртуального DOM и серверного рендера' },
    { name: 'Предварительная загрузка данных', timeDays: 3, costRub: 85000, effectMs: 210, description: 'Загрузка данных до рендеринга' },
    { name: 'Использование Streamed SSR', timeDays: 5, costRub: 140000, effectMs: 280, description: 'Отправка частей страницы потоком' },
    { name: 'Минимизация запросов к базе из SSR', timeDays: 4, costRub: 110000, effectMs: 230, description: 'Оптимизация запросов и кеширование' },
    { name: 'Отложенная отрисовка (Defer SSR)', timeDays: 3, costRub: 90000, effectMs: 190, description: 'Рендеринг неважных частей позже' },
    { name: 'Использование CDN для SSR', timeDays: 3, costRub: 80000, effectMs: 170, description: 'Быстрая доставка SSR-страниц' },
    { name: 'Локализация на уровне SSR', timeDays: 4, costRub: 120000, effectMs: 220, description: 'Оптимизация локализации для уменьшения нагрузки' },
    { name: 'Использование HTTP/2 для SSR', timeDays: 2, costRub: 60000, effectMs: 140, description: 'Быстрая загрузка SSR-запросов' },
    { name: 'Оптимизация Node.js сервера', timeDays: 5, costRub: 150000, effectMs: 300, description: 'Ускорение серверной части SSR' },
    { name: 'Внедрение lazy loading компонентов SSR', timeDays: 4, costRub: 110000, effectMs: 250, description: 'Отложенная загрузка неважных компонентов' },
    { name: 'Оптимизация работы с cookie на SSR', timeDays: 3, costRub: 70000, effectMs: 140, description: 'Минимизация данных cookie для SSR' },
    { name: 'Использование HTTP Cache-Control для SSR', timeDays: 3, costRub: 80000, effectMs: 180, description: 'Настройка кеширования SSR-ответов' },
    { name: 'Оптимизация статических ресурсов SSR', timeDays: 2, costRub: 60000, effectMs: 130, description: 'Уменьшение размера статических файлов' },
    { name: 'Анализ и профилирование SSR', timeDays: 4, costRub: 110000, effectMs: 200, description: 'Анализ узких мест и оптимизация' },
    { name: 'Переписывание SSR на более быстрый язык', timeDays: 8, costRub: 250000, effectMs: 400, description: 'Использование компилируемых языков, например Rust' },
    { name: 'Оптимизация логирования SSR', timeDays: 3, costRub: 70000, effectMs: 140, description: 'Минимизация влияния логов на производительность' },
  ]],
  ['network', [
    { name: 'Оптимизация TCP-коннекций', timeDays: 3, costRub: 90000, effectMs: 190, description: 'Уменьшение времени установки соединения' },
    { name: 'Использование HTTP/3 (QUIC)', timeDays: 6, costRub: 200000, effectMs: 350, description: 'Быстрый и надёжный протокол передачи данных' },
    { name: 'Сжатие данных (gzip, brotli)', timeDays: 2, costRub: 60000, effectMs: 130, description: 'Уменьшение объёма передаваемых данных' },
    { name: 'Оптимизация DNS-запросов', timeDays: 2, costRub: 50000, effectMs: 120, description: 'Сокращение времени резолвинга DNS' },
    { name: 'Использование CDN', timeDays: 5, costRub: 150000, effectMs: 320, description: 'Ближайшая доставка контента' },
    { name: 'Минимизация редиректов', timeDays: 1, costRub: 30000, effectMs: 90, description: 'Сокращение количества редиректов' },
    { name: 'Предварительная установка соединения (Preconnect)', timeDays: 2, costRub: 60000, effectMs: 140, description: 'Ускорение установления соединений' },
    { name: 'Оптимизация Keep-Alive', timeDays: 1, costRub: 40000, effectMs: 100, description: 'Поддержка постоянных соединений' },
    { name: 'Удаление лишних заголовков', timeDays: 1, costRub: 35000, effectMs: 80, description: 'Уменьшение объёма HTTP-заголовков' },
    { name: 'Использование HTTP/2 Server Push', timeDays: 3, costRub: 90000, effectMs: 210, description: 'Предварительная отправка ресурсов' },
    { name: 'Настройка кеширования через Cache-Control', timeDays: 3, costRub: 85000, effectMs: 180, description: 'Управление кешированием' },
    { name: 'Оптимизация TLS handshake', timeDays: 4, costRub: 110000, effectMs: 220, description: 'Сокращение времени TLS рукопожатия' },
    { name: 'Внедрение CDN с геораспределением', timeDays: 5, costRub: 160000, effectMs: 300, description: 'Географически распределённые точки присутствия' },
    { name: 'Использование прокси', timeDays: 4, costRub: 130000, effectMs: 250, description: 'Уменьшение задержек через прокси' },
    { name: 'Оптимизация загрузки шрифтов', timeDays: 2, costRub: 60000, effectMs: 140, description: 'Быстрая загрузка и кеширование шрифтов' },
    { name: 'Оптимизация изображений (CDN + lazy)', timeDays: 3, costRub: 80000, effectMs: 180, description: 'Оптимальная доставка и загрузка' },
    { name: 'Использование DNS Prefetch', timeDays: 1, costRub: 35000, effectMs: 70, description: 'Предзагрузка DNS-запросов' },
    { name: 'Настройка HSTS', timeDays: 1, costRub: 40000, effectMs: 90, description: 'Повышение безопасности и скорости HTTPS' },
    { name: 'Использование HTTP Cache Validation', timeDays: 3, costRub: 75000, effectMs: 150, description: 'Уменьшение объёма повторных запросов' },
    { name: 'Оптимизация загрузки критического пути', timeDays: 4, costRub: 100000, effectMs: 230, description: 'Минимизация ресурсов для первого отображения' },
  ]],
  ['backend', [
    { name: 'Оптимизация запросов к базе данных', timeDays: 6, costRub: 180000, effectMs: 320, description: 'Улучшение и оптимизация SQL-запросов' },
    { name: 'Кеширование на уровне сервера', timeDays: 5, costRub: 150000, effectMs: 280, description: 'Кеширование часто запрашиваемых данных' },
    { name: 'Масштабирование серверов', timeDays: 8, costRub: 250000, effectMs: 400, description: 'Добавление серверных мощностей' },
    { name: 'Оптимизация бизнес-логики', timeDays: 5, costRub: 150000, effectMs: 270, description: 'Снижение количества операций' },
    { name: 'Использование кеша Redis/Memcached', timeDays: 6, costRub: 200000, effectMs: 320, description: 'Быстрый доступ к временным данным' },
    { name: 'Оптимизация сериализации данных', timeDays: 4, costRub: 110000, effectMs: 200, description: 'Быстрая сериализация и десериализация данных' },
    { name: 'Минимизация вызовов к внешним API', timeDays: 3, costRub: 90000, effectMs: 170, description: 'Сокращение обращений к внешним сервисам' },
    { name: 'Внедрение мониторинга и алертинга', timeDays: 2, costRub: 60000, effectMs: 120, description: 'Быстрое выявление проблем' },
    { name: 'Оптимизация работы с файлами', timeDays: 4, costRub: 100000, effectMs: 210, description: 'Быстрая работа с файловой системой' },
    { name: 'Использование HTTP/2 для API', timeDays: 3, costRub: 80000, effectMs: 150, description: 'Быстрая передача данных' },
    { name: 'Оптимизация использования памяти', timeDays: 5, costRub: 140000, effectMs: 230, description: 'Уменьшение использования памяти' },
    { name: 'Использование пулов соединений', timeDays: 4, costRub: 110000, effectMs: 200, description: 'Эффективное управление подключениями' },
    { name: 'Внедрение очередей сообщений', timeDays: 6, costRub: 180000, effectMs: 300, description: 'Асинхронная обработка задач' },
    { name: 'Обновление серверного ПО', timeDays: 3, costRub: 70000, effectMs: 150, description: 'Использование новых версий с улучшениями производительности' },
    { name: 'Оптимизация аутентификации', timeDays: 3, costRub: 80000, effectMs: 170, description: 'Быстрая и безопасная аутентификация' },
    { name: 'Использование контейнеризации', timeDays: 5, costRub: 160000, effectMs: 250, description: 'Упрощение развертывания и масштабирования' },
    { name: 'Оптимизация кэширования HTTP-ответов', timeDays: 4, costRub: 110000, effectMs: 210, description: 'Эффективное кеширование ответов API' },
    { name: 'Настройка rate limiting', timeDays: 2, costRub: 60000, effectMs: 130, description: 'Ограничение количества запросов для защиты и стабильности' },
    { name: 'Использование профилирования', timeDays: 5, costRub: 140000, effectMs: 240, description: 'Анализ и устранение узких мест' },
  ]],
  ['proxy', [
    { name: 'Внедрение CDN', timeDays: 5, costRub: 150000, effectMs: 300, description: 'Использование CDN для кеширования статики и уменьшения времени ответа' },
    { name: 'Настройка обратного прокси', timeDays: 4, costRub: 120000, effectMs: 260, description: 'Балансировка нагрузки и кеширование' },
    { name: 'Оптимизация SSL/TLS на прокси', timeDays: 3, costRub: 90000, effectMs: 200, description: 'Ускорение SSL рукопожатия' },
    { name: 'Использование HTTP/2 на прокси', timeDays: 3, costRub: 85000, effectMs: 180, description: 'Ускорение передачи данных' },
    { name: 'Настройка кеширования на прокси', timeDays: 4, costRub: 110000, effectMs: 230, description: 'Кеширование динамического и статического контента' },
    { name: 'Внедрение защиты от DDoS', timeDays: 5, costRub: 160000, effectMs: 280, description: 'Фильтрация вредоносного трафика' },
    { name: 'Использование прокси для сжатия трафика', timeDays: 3, costRub: 90000, effectMs: 190, description: 'Уменьшение объёма передаваемых данных' },
    { name: 'Оптимизация времени отклика прокси', timeDays: 4, costRub: 120000, effectMs: 250, description: 'Сокращение задержек' },
    { name: 'Настройка балансировки нагрузки', timeDays: 5, costRub: 150000, effectMs: 270, description: 'Распределение трафика между серверами' },
    { name: 'Мониторинг и алертинг прокси', timeDays: 3, costRub: 80000, effectMs: 160, description: 'Отслеживание проблем и предупреждения' },
    { name: 'Оптимизация кэширования заголовков', timeDays: 3, costRub: 85000, effectMs: 180, description: 'Управление кешем HTTP-заголовков' },
    { name: 'Внедрение HTTP/3 на прокси', timeDays: 6, costRub: 200000, effectMs: 320, description: 'Использование нового протокола передачи данных' },
    { name: 'Оптимизация TCP-параметров на прокси', timeDays: 4, costRub: 110000, effectMs: 210, description: 'Уменьшение задержек и потерь' },
    { name: 'Использование Web Application Firewall', timeDays: 5, costRub: 170000, effectMs: 290, description: 'Защита веб-приложений на уровне прокси' },
    { name: 'Внедрение HTTP/2 Server Push на прокси', timeDays: 3, costRub: 90000, effectMs: 200, description: 'Ускорение загрузки ресурсов' },
    { name: 'Оптимизация обработки Keep-Alive', timeDays: 2, costRub: 60000, effectMs: 130, description: 'Поддержка постоянных соединений' },
    { name: 'Оптимизация сжатия Brotli на прокси', timeDays: 3, costRub: 85000, effectMs: 180, description: 'Уменьшение размера передаваемых данных' },
    { name: 'Использование прокси кеширования API', timeDays: 4, costRub: 120000, effectMs: 240, description: 'Кеширование API-запросов на прокси' },
    { name: 'Оптимизация прокси для HTTP Keep-Alive', timeDays: 2, costRub: 60000, effectMs: 140, description: 'Снижение накладных расходов на соединения' },
    { name: 'Внедрение прокси для WebSocket', timeDays: 4, costRub: 130000, effectMs: 260, description: 'Поддержка WebSocket через прокси' },
  ]],
  ['database', [
    { name: 'Индексация часто используемых полей', timeDays: 5, costRub: 120000, effectMs: 300, description: 'Создание индексов для ускорения запросов' },
    { name: 'Оптимизация запросов SELECT', timeDays: 6, costRub: 140000, effectMs: 320, description: 'Переписывание запросов для скорости' },
    { name: 'Использование партиционирования таблиц', timeDays: 7, costRub: 160000, effectMs: 350, description: 'Разделение таблиц для масштабирования' },
    { name: 'Оптимизация транзакций', timeDays: 5, costRub: 130000, effectMs: 280, description: 'Минимизация блокировок и задержек' },
    { name: 'Использование репликации', timeDays: 8, costRub: 200000, effectMs: 400, description: 'Расширение масштабируемости чтения' },
    { name: 'Внедрение кеша запросов', timeDays: 4, costRub: 100000, effectMs: 250, description: 'Кеширование часто выполняемых запросов' },
    { name: 'Оптимизация структуры таблиц', timeDays: 6, costRub: 150000, effectMs: 300, description: 'Нормализация или денормализация для скорости' },
    { name: 'Использование сжатия данных', timeDays: 3, costRub: 90000, effectMs: 200, description: 'Уменьшение объёма хранения и передачи' },
    { name: 'Мониторинг производительности БД', timeDays: 3, costRub: 80000, effectMs: 180, description: 'Отслеживание и устранение узких мест' },
    { name: 'Автоматическое архивирование старых данных', timeDays: 4, costRub: 110000, effectMs: 220, description: 'Снижение нагрузки на основные таблицы' },
    { name: 'Оптимизация индексов', timeDays: 5, costRub: 120000, effectMs: 270, description: 'Удаление неиспользуемых и добавление нужных' },
    { name: 'Использование In-Memory БД', timeDays: 7, costRub: 180000, effectMs: 350, description: 'Быстрый доступ к часто используемым данным' },
    { name: 'Оптимизация соединений к БД', timeDays: 3, costRub: 85000, effectMs: 190, description: 'Пулы соединений и правильное закрытие' },
    { name: 'Использование аналитических индексов', timeDays: 4, costRub: 110000, effectMs: 230, description: 'Ускорение аналитических запросов' },
    { name: 'Оптимизация схемы данных', timeDays: 5, costRub: 140000, effectMs: 260, description: 'Изменение схемы для быстрого доступа' },
    { name: 'Использование NoSQL для кеширования', timeDays: 4, costRub: 100000, effectMs: 210, description: 'Кеширование данных в NoSQL хранилищах' },
    { name: 'Оптимизация бэкапов', timeDays: 3, costRub: 75000, effectMs: 170, description: 'Быстрое резервное копирование и восстановление' },
    { name: 'Автоматизация обслуживания БД', timeDays: 5, costRub: 130000, effectMs: 240, description: 'Плановое обслуживание и оптимизация' },
    { name: 'Использование компрессии запросов', timeDays: 3, costRub: 80000, effectMs: 180, description: 'Снижение объема передаваемых данных' },
    { name: 'Оптимизация запросов JOIN', timeDays: 6, costRub: 150000, effectMs: 310, description: 'Снижение времени выполнения сложных запросов' },
  ]],
]);